version: '3'
services:
  vue-client:
    build: ./client
    command: http-server dist
    ports:
      - "8090:8080"
    depends_on:
      - node-server
    restart: always

  node-server:
    build: ./server
    command: npm run serve
    ports:
      - "9000:9000"
    restart: always